databases:
  - name: vespa-database
    databaseName: vespa_database
    user: vespa_database_user

services:
  - type: web
    name: booking-api
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vespa-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
