default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: booking_development

test:
  <<: *default
  database: booking_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
